export const DEFAULT_SENTENCE_RADIUS = 450;
export const DEFAULT_WORD_RADIUS = 100;
export const DEFAULT_CONSONANT_RADIUS = 50;
export const DEFAULT_VOCAL_RADIUS = 20;
export const DEFAULT_DOT_RADIUS = 5;
